// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJvGZBXJRZNpvSp1MCzf2YZrL_toI--tc',
    appId: '1:38030892046:web:8f55cf1031a4849d4d305f',
    messagingSenderId: '38030892046',
    projectId: 'readly-41',
    authDomain: 'readly-41.firebaseapp.com',
    storageBucket: 'readly-41.firebasestorage.app',
    measurementId: 'G-BEXF0CNCXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIFEALLEJ0-w-4TFTrOgNKQkIKgxrOMM',
    appId: '1:38030892046:android:de6bf94ffd05dd2b4d305f',
    messagingSenderId: '38030892046',
    projectId: 'readly-41',
    storageBucket: 'readly-41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7YRI5GXbHyMW0zBCV6PNAl-CnZ9CF2o',
    appId: '1:38030892046:ios:7cad3d5d4379e2af4d305f',
    messagingSenderId: '38030892046',
    projectId: 'readly-41',
    storageBucket: 'readly-41.firebasestorage.app',
    iosBundleId: 'com.example.readly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7YRI5GXbHyMW0zBCV6PNAl-CnZ9CF2o',
    appId: '1:38030892046:ios:7cad3d5d4379e2af4d305f',
    messagingSenderId: '38030892046',
    projectId: 'readly-41',
    storageBucket: 'readly-41.firebasestorage.app',
    iosBundleId: 'com.example.readly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJvGZBXJRZNpvSp1MCzf2YZrL_toI--tc',
    appId: '1:38030892046:web:f9327b3606d947e44d305f',
    messagingSenderId: '38030892046',
    projectId: 'readly-41',
    authDomain: 'readly-41.firebaseapp.com',
    storageBucket: 'readly-41.firebasestorage.app',
    measurementId: 'G-SCNK1LK73C',
  );
}
